# Generated by Django 5.1.15 on 2026-06-08 22:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('chicken', 'Chicken'), ('duck', 'Duck'), ('goose', 'Goose'), ('turkey', 'Turkey'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('pig', 'Pig'), ('cow', 'Cow'), ('rabbit', 'Rabbit'), ('bees', 'Bee colony'), ('other', 'Other')], default='chicken', max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('acquired_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True, help_text='Untick when the animal leaves the holding.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PotatoPlanting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('first_early', 'First early'), ('second_early', 'Second early'), ('maincrop', 'Maincrop'), ('salad', 'Salad')], default='maincrop', max_length=20)),
                ('planted_on', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Number of seed potatoes.', null=True)),
                ('bed', models.CharField(blank=True, help_text='Bed / row / location.', max_length=120)),
                ('expected_harvest', models.DateField(blank=True, help_text='Override the estimated harvest date.', null=True)),
                ('harvested_on', models.DateField(blank=True, null=True)),
                ('yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-planted_on'],
            },
        ),
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('recurrence_interval_days', models.PositiveIntegerField(default=7, help_text='How often this task repeats, in days.')),
                ('last_completed', models.DateField(blank=True, help_text='When the task was last done. Drives the next due date.', null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(blank=True, help_text="Leave blank for whole-holding tasks (e.g. 'clean the coop').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_tasks', to='tracker.animal')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EggRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(blank=True, help_text='Optional coop or flock name.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'source'), name='unique_egg_record_per_day_source')],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('general', 'General'), ('health', 'Health'), ('feeding', 'Feeding'), ('breeding', 'Breeding'), ('task_completed', 'Task completed')], default='general', max_length=20)),
                ('note', models.TextField()),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='tracker.animal')),
                ('care_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='tracker.caretask')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
    ]
