# Generated by Django 5.1.15 on 2026-06-08 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='caretask',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text="Who's responsible. Leave blank for anyone.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_tasks', to='tracker.person'),
        ),
    ]
