# Generated by Django 5.1.15 on 2026-06-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_person_caretask_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('chicken', 'Chicken'), ('duck', 'Duck'), ('goose', 'Goose'), ('turkey', 'Turkey'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('pig', 'Pig'), ('cow', 'Cow'), ('rabbit', 'Rabbit'), ('bees', 'Bee colony'), ('horse', 'Horse'), ('tortoise', 'Tortoise'), ('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], default='chicken', max_length=20),
        ),
    ]
