# Generated by Django 5.1.15 on 2026-06-09 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_animal_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(help_text="Catalog key, e.g. 'carrots'.", max_length=50)),
                ('variety', models.CharField(blank=True, max_length=120)),
                ('planted_on', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Number planted/sown.', null=True)),
                ('bed', models.CharField(blank=True, help_text='Bed / row / location.', max_length=120)),
                ('expected_harvest', models.DateField(blank=True, help_text='Override the estimated harvest date.', null=True)),
                ('harvested_on', models.DateField(blank=True, null=True)),
                ('yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-planted_on'],
            },
        ),
        migrations.DeleteModel(
            name='PotatoPlanting',
        ),
    ]
