# Generated by Django 5.1.15 on 2026-06-09 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who wrote the note. Blank for system entries (task completions, harvests).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='tracker.person'),
        ),
    ]
