# Generated by Django 5.1.15 on 2026-06-09 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_logentry_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField()),
            ],
            options={
                'ordering': ['-fetched_at'],
                'get_latest_by': 'fetched_at',
            },
        ),
    ]
