# Generated by Django 5.1.15 on 2026-06-12 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretask',
            name='times_done',
            field=models.PositiveIntegerField(default=0, help_text='Completions recorded on last_completed — progress through a several-times-a-day task.'),
        ),
        migrations.AddField(
            model_name='caretask',
            name='times_per_day',
            field=models.PositiveIntegerField(default=1, help_text='How many times the task needs doing on its due day, e.g. 4 for a dog fed four times a day.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
