# Generated by Django 5.1.15 on 2026-06-14 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_chicken_egg_check_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretask',
            name='due_time',
            field=models.TimeField(blank=True, help_text='Optional clock time the task is due / its reminder fires, e.g. 07:30 to feed the dog. Blank = anytime that day (e.g. collect the eggs).', null=True),
        ),
        migrations.CreateModel(
            name='PushReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timed_reminders', to='tracker.caretask')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timed_reminders', to='tracker.pushsubscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subscription', 'care_task', 'sent_date'), name='unique_timed_reminder_per_day')],
            },
        ),
    ]
