# Generated by Django 5.1.15 on 2026-06-14 11:37

from django.db import migrations, models


def backfill_species(apps, schema_editor):
    """Tag existing species-routine tasks with their species so type-level jobs
    (e.g. the chicken egg check) read as belonging to the whole type. Their
    auto_key is "animal:<species>:<job>" (3 parts); per-animal generic routines
    carry the pk too ("animal:<species>:<pk>:<job>") and are left alone.

    These jobs also lose any individual ``animal`` link: migration 0011 pinned the
    egg check to the first hen, but it belongs to all the chickens, so clear it."""
    CareTask = apps.get_model("tracker", "caretask")
    valid = {code for code, _ in CareTask._meta.get_field("species").choices}
    for task in CareTask.objects.filter(auto_key__startswith="animal:", species=""):
        parts = task.auto_key.split(":")
        if len(parts) == 3 and parts[1] in valid:
            task.species = parts[1]
            task.animal = None
            task.save(update_fields=["species", "animal"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_caretask_due_time_pushreminderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretask',
            name='species',
            field=models.CharField(blank=True, choices=[('chicken', 'Chicken'), ('duck', 'Duck'), ('goose', 'Goose'), ('turkey', 'Turkey'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('pig', 'Pig'), ('cow', 'Cow'), ('rabbit', 'Rabbit'), ('bees', 'Bee colony'), ('horse', 'Horse'), ('tortoise', 'Tortoise'), ('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], db_index=True, default='', help_text='Assign to a whole animal type (e.g. all chickens — collecting the eggs) rather than one individual. Leave blank for a single-animal (see `animal`) or whole-holding job.', max_length=20),
        ),
        migrations.RunPython(backfill_species, noop),
    ]
