# Generated by Django 5.1.15 on 2026-06-17 21:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0013_caretask_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="medicine",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Medicine/treatment given, if any.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="logentry",
            name="withdrawal_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Days after treatment that eggs/meat must not be eaten.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="WeightRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_records",
                        to="tracker.animal",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
