# Generated by Django 5.1.15 on 2026-06-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0014_logentry_medicine_logentry_withdrawal_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caretask",
            name="snoozed_until",
            field=models.DateField(
                blank=True,
                help_text="'Remind me later': hold the task back until this date. Cleared automatically when the task is completed.",
                null=True,
            ),
        ),
    ]
