# Generated by Django 5.1.15 on 2026-06-17 22:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0015_caretask_snoozed_until"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit it's counted in, e.g. kg, bags, bales.",
                        max_length=30,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "reorder_at",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Flag as low when quantity drops to or below this.",
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "supplies",
                "ordering": ["name"],
            },
        ),
    ]
