# Generated by Django 5.1.15 on 2026-06-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0016_supply"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="animals/"),
        ),
        migrations.AddField(
            model_name="crop",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="crops/"),
        ),
    ]
